### ISSUE TITLE
FYI: will not fully support upcoming Spark Mollie edition

### ISSUE THREAD

**Issue by sandervanhooft** [centrality-labs/spark-tailwindcss#4]
Man, I love this!

But unfortunately it will not cover all Spark-Mollie screens (to be released, probably April). I had to modify some views, and decided with Taylor to keep spark-mollie in a separate branch.

Just so you know / avoid any upcoming confusion. Perhaps I/someone else can find the time to either fork or adapt this package.

**Comment by iantasker** [comment]
@sandervanhooft Thanks. 

I haven't used mollie so haven't looked at coverage. If you would like fork the repo feel free, if you would like to me to host it and are willing to help get the coverage I will spin up a dedicated repo.
