### ISSUE TITLE
Errror with npm install && npm run dev

### ISSUE THREAD

**Issue by shaunthornburgh** [centrality-labs/spark-tailwindcss#6]
I have just installed the Laravel 7 version. I am able to run `php artisan ui spark-tailwindcss`

But when I run `npm install && npm run dev` I get the following error:

```
ERROR in multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css
Module not found: Error: Can't resolve '/Users/shaunthornburgh/Development/praise/src/resources/css/tailwind.css' in '/Users/shaunthornburgh/Development/praise/src'
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css /js/app[3]

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css
Module not found: Error: Can't resolve '/Users/shaunthornburgh/Development/praise/src/resources/sass/app-rtl.scss' in '/Users/shaunthornburgh/Development/praise/src'
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css /js/app[2]

ERROR in multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css
Module not found: Error: Can't resolve '/Users/shaunthornburgh/Development/praise/src/resources/sass/app.scss' in '/Users/shaunthornburgh/Development/praise/src'
 @ multi ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/app-rtl.scss ./resources/css/tailwind.css /js/app[1]
```

Here is my webpack.mix.js: 

```
let mix = require('laravel-mix');
require('laravel-mix-purgecss');
let exec = require('child_process').exec;
let path = require('path');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
    .sass('resources/sass/app.scss', 'public/css')
    .js('resources/js/app.js', 'public/js')
    .copy('node_modules/sweetalert2/dist/sweetalert2.min.js', 'public/js/sweetalert.min.js')
    .sass('resources/sass/app-rtl.scss', 'public/css')
    .then(() => {
        exec('node_modules/rtlcss/bin/rtlcss.js public/css/app-rtl.css ./public/css/app-rtl.css');
    })
    .webpackConfig({
        resolve: {
            modules: [
                path.resolve(__dirname, 'vendor/laravel/spark-aurelius/resources/assets/js'),
                'node_modules'
            ],
            alias: {
                'vue$': mix.inProduction() ? 'vue/dist/vue.min' : 'vue/dist/vue.js'
            }
        }
    });


if (mix.inProduction()) {
    mix.version();
}


mix.postCss('resources/css/tailwind.css', 'public/css/app.css', [
    require('postcss-import'),
    require('tailwindcss'),
]);

if (mix.inProduction()) {
    mix.purgeCss();
}
```

Any idea what is going wrong here?

**Comment by iantasker** [comment]
Hi @shaunthornburgh 

Thanks for reporting this, it looks like the stubbed `tailwind.css` file is not being copied over. 

I will fix this asap but in the interim copy this file https://github.com/centrality-labs/spark-tailwindcss/blob/master/src/spark-tailwindcss-stubs/resources/css/tailwind.css into your `resourses/css` folder and it should compile correctly.

**Comment by shaunthornburgh** [comment]
Thanks @iantasker , I copied this across `tailwind.css`. I also had to copy `bootstrap4-shim.css` and `'bootstrap-custom.css`. I then had to restore `sass/app.scss` and `sass/app-rtl.scss` from `vendor/laravel/spark-aurelius` in order to get it to compile. However the spark app has now lost it's styling.

<img width="1261" alt="Screenshot 2020-05-04 at 23 22 30" src="https://user-images.githubusercontent.com/3660684/81019369-6d4c2c00-8e5e-11ea-80db-79b6257aa011.png">

PHPStorm is also highlighting a css issues 

`app/css`
![Screenshot 2020-05-04 at 23 23 11](https://user-images.githubusercontent.com/3660684/81019361-69200e80-8e5e-11ea-9747-720d97693299.png)

`tailwind.css`
<img width="441" alt="Screenshot 2020-05-04 at 23 56 54" src="https://user-images.githubusercontent.com/3660684/81021452-1563f400-8e63-11ea-9a57-c83345a16404.png">

`bootstrap4-shim.css`
<img width="545" alt="Screenshot 2020-05-04 at 23 53 36" src="https://user-images.githubusercontent.com/3660684/81021206-8c4cbd00-8e62-11ea-86ec-c50873a531c4.png">

Is there anything else I need to copy over to finish the install?

**Comment by iantasker** [comment]
@shaunthornburgh It looks like your `composer.json` file hasn't updated.  Please add the following and run a compose update. 

```
'laravel-mix' => '^4.0.14',
'laravel-mix-purgecss' => '^4.1',
'postcss-import' => '^12.0.1',
'tailwindcss' => '^1.4',
```

You should be able to then run `npm install && npm run dev`

**Comment by shaunthornburgh** [comment]
Thanks @iantasker, I have tried this, but when I run `composer update` I get the following:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel-mix could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package laravel-mix-purgecss could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package postcss-import could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package tailwindcss could not be found in any version, there may be a typo in the package name.`

**Comment by iantasker** [comment]
@shaunthornburgh I will spin up a new spark project tonight and get to the bottom of this!

**Comment by shaunthornburgh** [comment]
Hi @iantasker, I have updated my composer.json to use the latest version `"centrality-labs/spark-tailwindcss": "2.2.1",` and ran 

```
composer update
php artisan ui spark-tailwindcss
npm install && npm run dev
```

However my views still seem to be broken, any ideas?
